#!/bin/bash

##--------------------------
# takes target FROM and TO positions, query cultivar's SNPs in vcf format as input, and generate a list of
# cultivars from 3kRGP as close-relatives of the query cultivar based on the best matched SNP profile (haplovars) as output.

source ./0SOURCE

# softlink vcf files
# For the findbySNP to work, it looks at the intersection of SNP positions
# of cultivar vcf against the SNP-Seek dataset.
# It is critical to make sure the SNP position in vcf files is in the format of "1 2345"
# as intersection of "OsjChr1 2345" and "1 2345" will not work apparently.
# The WGvarSNP generates vcf files with OsjChr1 for chromosome1.
# Change the CHR name from "OsjChr1" to "1" for vcf files.

cd ${findbySNP_DIR}
mkdir -p run/ThaRegGA
cd run/ThaRegGA
for file in ${SAMPLE}
    do ln -s ${SNP_DIR}/gatk_${file}_env_snp.vcf .
    sed -i 's/^OsjChr//' gatk_${file}_env_snp.vcf
done

# Restrict SNPs to the target region defined by TARGET, REFERENCE, FROM, and TO in 0SOURCE of TRegGA, such as:
# TARGET=OsjSWEET13
# REFERENCE=OsjCHR12
# FROM=17292001
# TO=17315000
# Modify REFERENCE so that it is consistent with the SNP-Seek convention for chromosome name.
echo $REFERENCE > tmp
REFERENCE=`sed 's/OsjCHR//' tmp`
for file in ${SAMPLE}
do
grep -w "^$REFERENCE" gatk_${file}_env_snp.vcf |\
awk -v from=${FROM} -v to=${TO} '{ if ( $2 >= from && $2 <= to ) print $0 }' > gatk_${file}_env_snp_${TARGET}.vcf
done

# cultivar identification
# Choose from these two SNP-Seek database, definedin 0SOURCE
# PLINKFNAME=${findbySNP_DIR}/data/NB-core_v4
# PLINKFNAME=${findbySNP_DIR}/data/3krg_filt_snp_v4

for file in ${SAMPLE}
    do python2 ${findbySNP_DIR}/src/identify.py ${PLINKFNAME} gatk_${file}_env_snp_${TARGET}.vcf > gatk_${file}_env_snp_${TARGET}.haplovar
done

# Report back to ThaRegGA
\cp *.haplovar ${TRegGA_DIR)/run

