#!/bin/bash

##--------------------------
# takes target FROM and TO positions, query cultivar's SNPs in vcf format as input, and generate a list of
# cultivars from 3kRGP as close-relatives of the query cultivar based on the best matched SNP profile (haplovars) as output.

source ./0SOURCE

# softlink vcf files
cd ${rice3k_DIR}
mkdir -p analysis/ThaRegGA
cd analysis/ThaRegGA
for file in ${SAMPLE}
    do ln -s ${SNP_DIR}/gatk_${file}_env_snp.vcf .
done

# cultivar identification
for file in ${SAMPLE}
    do python2 ${rice3k_DIR}/scripts/identify.py ${PLINKFNAME} gatk_${file}_env_snp.vcf > ${file}_Haplovar.results
done

